spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

encryption:
  aes:
    secret-key: ${ENCRYPTION_SECRET_KEY}
    algorithm: ${ENCRYPTION_ALGORITHM}